version = "1.0"

[main]
name = "Lufi configuration"
services = ["__APP__"]

    [main.config]
    name = "Configuration Options"

        [main.config.max_file_size]
        ask = "Max file size"
        type = "number"
        default = 100000000
        help = "Choose the maximum file size allowed to send, in bytes (0 = no limit, default is 100000000=100MB)"
        bind = "max_file_size:__INSTALL_DIR__/lufi.conf"