test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.use_ldap=0

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4311a7ac2df01a866bd50a83fbdb95b9c1c154ef.name = "Upgrade from 0.05.21~ynh1"
