#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers
#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

secret=$(ynh_string_random --length=24)
max_file_size=100
use_ldap=$YNH_APP_ARG_USE_LDAP

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --key=use_ldap --value=$use_ldap
ynh_app_setting_set --key=max_file_size --value=$max_file_size
ynh_app_setting_set --key=secret --value=$secret

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

yunohost service add $app --description="Lufi service" --log="$install_dir/log/production.log"

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"
chmod +x $install_dir/script/lufi

#=================================================
# CONFIGURE LUFI
#=================================================
ynh_script_progression "Configuring $app..."

ldap="#"
if [ $use_ldap -eq 1 ];
then
	ldap=""
fi

ynh_config_add --template="lufi.conf" --destination="$install_dir/lufi.conf"

chmod 600 $install_dir/lufi.conf
chown $app:$app $install_dir/lufi.conf

#=================================================
# INSTALL LUFI
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
	# Patch cpanfile.snapshot to bump dependency
	sed -i 's|Cpanel-JSON-XS-4.19|Cpanel-JSON-XS-4.37|' cpanfile.snapshot
	sed -i 's|Cpanel::JSON::XS 4.19|Cpanel::JSON::XS 4.37|' cpanfile.snapshot
	carton install --deployment --without=sqlite  --without=mysql --without=htpasswd --without=test
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start" --wait_until="Creating process id file" --log_path="$install_dir/log/production.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
