#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=max_file_size --value=100 # 100 Mo
ynh_app_setting_set_default --key=use_ldap --value=0
ynh_app_setting_set_default --key=secret --value=$(ynh_string_random --length=24)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="lufi.conf""

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ldap="#"
if [ $use_ldap -eq 1 ];
then
	ldap=""
fi

ynh_config_add --template="lufi.conf" --destination="$install_dir/lufi.conf"

chmod 600 $install_dir/lufi.conf
chown $app:$app $install_dir/lufi.conf

#=================================================
# BUILD LUFI
#=================================================
ynh_script_progression "Building Lufi..."

pushd $install_dir
	# Patch cpanfile.snapshot to bump dependency
	sed -i 's|Cpanel-JSON-XS-4.19|Cpanel-JSON-XS-4.37|' cpanfile.snapshot
	sed -i 's|Cpanel::JSON::XS 4.19|Cpanel::JSON::XS 4.37|' cpanfile.snapshot
	ynh_hide_warnings carton install --deployment --without=sqlite --without=mysql --without=htpasswd --without=test
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Lufi service" --log="$install_dir/log/production.log"

ynh_config_add_logrotate


ynh_config_add --template="cron" --destination="/etc/cron.d/$app"
chmod +x $install_dir/script/lufi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Web application available"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
